### PR TITLE
make metric port configurable

### PR DESCRIPTION
**Pull request by D3luxee**
Hi, 
thanks for this tool! 
I've made the metric port configurable to get it working in my setup ;)

The setting is optional and defaults to the previous setting.

Maybe you can answer one of my questions, is the image somewhere publicly available?

### CODE REVIEW

**Comment by TaylorMutch** [comment]
Thanks for the contribution!

> Maybe you can answer one of my questions, is the image somewhere publicly available?

Currently no, but you're welcome to build and host one for your purposes! If I find time I may put one up.

**Review by TaylorMutch — COMMENTED** [review]
@D3luxee Since there's not really any other port served by this, what do you think about just using `Port`?

**Comment by D3luxee** [comment]
I've change it to `Port` should be fine now.

**Review by TaylorMutch — APPROVED** [review]
Great!

**Pull request merged**
